### ISSUE TITLE
eartube file

### ISSUE THREAD

**Issue by j0en0** [GliaX/Stethoscope#35] opened 2016-09-05 20:00 UTC
I'm having a few issues with the eartube file, the segments don't seem to be meshed together properly and they come out separate in the output file. The source file for eartube isn't in the master folder. Is there a way to get the source file? 
Regards

**Comment by tareko** [comment] 2016-09-05 22:35
Hello @j0en0,

Could you take some screenshots or describe how to create this? Are you using the "eartube.stl" file in the base directory of the repo?

The source file is created like [here](https://github.com/GliaX/Stethoscope#changing-and-creating-scad-files), I believe.

@Joaz I vaguely recall that when I looked we were missing the final eartube file? Could you double-check?

@alawx did make an OpenSCAD version of the eartube. @Alawx: Could you upload it?

tarek : )

**Comment by j0en0** [comment] 2016-09-06 19:21
Hi @tareko 

Yup, I am using the "eartube.stl" file from the master branch of the base directory. I have attached the screen shots. 
Thanks
Jono
[screenshots.pdf](https://github.com/GliaX/Stethoscope/files/457576/screenshots.pdf)

**Comment by tareko** [comment] 2016-09-06 19:22
Interesting. Which slicer?

**Comment by redsqrly** [comment] 2016-09-06 19:47
Hey @tareko,

Im printing the model for @j0en0 and having the issues with the eartube.stl. Im using Simplify3D, ive tried to find a way to fix it in Meshmixer but all i know is that it isnt a non-manifold issue. The min thickness tool highlights a number of areas also. 

Kind regards,
Kirill

**Comment by tareko** [comment] 2016-09-06 19:52
@redsqrly: Thank you for the information. Do you mind trying to slice with [Slic3r](http://slic3r.org) and telling me what happens? @Joaz Any thoughts?

I usually use slic3r and haven't had issues with the model myself.

**Comment by redsqrly** [comment] 2016-09-06 20:34
@tareko No probs! Worked in Slic3r, i can see a couple of voids in infill in two or so layers but the walls are solid. I used to swear by Slic3r and love the fact its opensource but Simplify3D is just that little bit more efficient, i think. 
The stl file looks completely smooth in Slic3r, yet in Meshmixer and Simplify3D each individual segment is visible, and i can actually separate them as 3 individual shells but not all the segments become shells, just the 3 so its impossible to move all of them closer together.

**Comment by tareko** [comment] 2016-09-06 20:35
Interesting. Can we consider this issue closed, or do you think there's something we can do with the STL to decrease the odds of this issue?

**Comment by redsqrly** [comment] 2016-09-06 20:48
I was thinking that the issue is with the mesh thickness as Meshmixer's thickness analysis tool highlights a number of areas which are below 0.5mm. 0,5mm is the minimum thickness i can manage due to my nozzle size but i believe 1mm minimum shell thickness is recommended for 3d printed models. Do you still have access to the original design file, would that be SCAD? And if so, could you try to adjust the shell thickness through OpenScad or try to generate the file again in case there was an error?

**Comment by redsqrly** [comment] 2016-09-06 20:51
![eartube mesh](https://cloud.githubusercontent.com/assets/11467948/18290608/150fd97e-747c-11e6-8b84-5e33ea7d0330.JPG)

**Comment by tareko** [comment] 2016-09-06 22:49
OK, I will close this unless @Joaz has something to say about the matter. I'll add a note that it's a known issue.

**Closed by tareko** 2016-09-06 22:49 UTC
Labels: bug

**Comment by redsqrly** [comment] 2016-09-07 13:26
@tareko ive ended up redrawing the eartube using the original stl for dimensions as the issue was still bugging me, pun intended :) Ive uploaded it to my fork, feel free to add it to your files if you'd like. The shape is almost the same, as close as i could get, and the dimensions are exactly the same.

**Comment by tareko** [comment] 2016-09-07 13:28
Thank you for this. What was your model made in? I see the STL in your tree, but not the source file.

**Comment by redsqrly** [comment] 2016-09-07 13:32
No probs, i used Autodesk's Fusion 360, what format would you like the source to be in?

**Comment by redsqrly** [comment] 2016-09-07 13:34
![tube differences](https://cloud.githubusercontent.com/assets/11467948/18313743/fda2e588-7507-11e6-94b3-84baa11c54fa.JPG)

It came out a little shorter as the spline was a couple of degrees out. This wont affect the performance, will it?
